In [212]:
print("Hello, World!")

Hello, World!


In [213]:
print("Bienvenidos a las prácticas de Python")

Bienvenidos a las prácticas de Python


Este es un segmento de texto
#Títulos
#Subtítulos
## Otros Subtítulos

In [214]:
nombre = "Juan"
edad = 25
altura = 1.80
es_estudiante = True


In [215]:
print(edad)

25


In [216]:
print(altura)

1.8


In [217]:
print(f"El ususario se llama {nombre}, tiene {edad} años de edad, mide {altura} metros")

El ususario se llama Juan, tiene 25 años de edad, mide 1.8 metros


In [218]:
mi_numero = 10
print(f"Número original: {mi_numero}")

mi_numero = 60
print(f"Número nuevo: {mi_numero}")

Número original: 10
Número nuevo: 60


In [219]:
num_int1 = 123
num_int2 = -57

In [220]:
num_float1 = 3.14
num_float2 = -0.16

In [221]:
bool_var1 = True
bool_var2 = False

In [222]:
bool_var1

True

In [223]:
bool_var1
bool_var2

False

In [224]:
bool_var2
bool_var1

True

In [225]:
print(bool_var1)
print(bool_var2)

True
False


In [226]:
list_numbers = [1, 2, 3, 4, 5]
list_strings = ["A", "B", "C", "D"]

In [227]:
list_strings[0]

'A'

In [228]:
list_numbers[0]

1

Para una lista (suponer que se llama X)
 
     X = [a1, a2, a3, a4, ..., an]
posicion:  0   1  2    3 ..... n-1


In [229]:
list_strings[2]

'C'

In [230]:
x = 5
y = 3
z = x + y  # Salida: z = 8
z = x * y  # Salida: z = 15

Operadores Lógicos

In [231]:
True and False

False

In [232]:
True or False

True

In [233]:
not False



True

In [234]:
not not False

False

## Estructura de Decisión

Si
If "Regla" : Secoloca la instrucción/operación que hará la máquina

In [297]:
edad = 45
if edad >= 18 :
    print("Eres mayor de edad")

Eres mayor de edad


In [298]:
edad >= 18

True

Sino, complemento del condicional Si

Si (condición):
    Lo que haga el programa
    
en caso contrario (else)
    lo que deba hacer

In [299]:
edad = 45
if edad >= 18 :
    print("Eres mayor de edad")
else:
    print("No eres mayor de edad")

Eres mayor de edad


In [300]:
edad = 12
if edad >= 18 :
    print("Eres mayor de edad")
else:
    print("No eres mayor de edad")

No eres mayor de edad


elif es una extensión del if

In [301]:
X = [1,2,3,4,5,6,7,8,9,10]
X

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [302]:
20/2

10.0

In [303]:
20%2

0

In [304]:
X[0]

1

In [305]:
if X[0]%23 == 0:
    print("El número es divisible por 3 y su resto es 0")
elif X[0]%3 == 1:
    print("El número no es divisible por 3 y su resto es 1") 
else:
    print("El número no es divisible por 3 y su resto es 2")       

El número no es divisible por 3 y su resto es 1


In [306]:
j = 5

if X[j] % 3 == 0:
    print("El número es divisible por 3 y su resto es 0")
elif X[j] % 3 == 1:
    print("El número no es divisible por 3 y su resto es 1") 
else:
    print("El número no es divisible por 3 y su resto es 2")       

El número es divisible por 3 y su resto es 0


Estructuras de repetición (bucles)

In [307]:
for i in range(5):
    print(i)


0
1
2
3
4


In [308]:
frutas = ["manzana", "banana", "cereza"]
for x in frutas:
    print(x)

manzana
banana
cereza


In [309]:
# Tratar de modificar la estructura para que funcones y diga si los elementos son divisibles por 3
X = [1,2,3,4,5,6,7,8,9,10]

for j in X:
    if j % 3 == 0:
        print(f"El número {j} es divisible por 3 y su resto es 0")
    elif j % 3 == 1:
        print(f"El número {j} no es divisible por 3 y su resto es 1") 
    else:
        print(f"El número {j} no es divisible por 3 y su resto es 2")       

El número 1 no es divisible por 3 y su resto es 1
El número 2 no es divisible por 3 y su resto es 2
El número 3 es divisible por 3 y su resto es 0
El número 4 no es divisible por 3 y su resto es 1
El número 5 no es divisible por 3 y su resto es 2
El número 6 es divisible por 3 y su resto es 0
El número 7 no es divisible por 3 y su resto es 1
El número 8 no es divisible por 3 y su resto es 2
El número 9 es divisible por 3 y su resto es 0
El número 10 no es divisible por 3 y su resto es 1


Mientras

Mientras

While (condicion):

Lo que haga el programa

condición auxiliar (condicion)


In [310]:
contador = 0

while contador < 5:
    print(contador)
    contador = contador + 1


0
1
2
3
4


In [311]:
contador = 0

while contador < 5:
    print(contador)
    contador += 1


0
1
2
3
4


In [312]:
### Longitud o tamaño de una lista

### len permite 

len(X)

10

la instrucción "type" permite identificar el tipo de objeto que estamos trabajando

In [313]:
type(X)

list

In [314]:
X1 = (1,2,3,4,5,6,7,8,9,10)


In [315]:
type(X1)

tuple

In [316]:
len(X1)


10

In [317]:
X2 = {"1", "2", "3", "4", "5","6", "7","8", "9", "10"}

type(X2)

set

In [318]:
len(X2)

10

In [319]:
X

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [320]:
X[6]

7

In [321]:
X[4]

5

Cada vez que se coloca X[j] estamos indicando al programa que me muestra el elemento de X está en la posición j

In [322]:
X1[2]

3

In [323]:
X1

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [324]:
X1[2]

3

In [325]:
X2

{'1', '10', '2', '3', '4', '5', '6', '7', '8', '9'}

In [326]:
# X = [1,2,3,4,5,6,7,8,9,10]
i = 0

while i < len(X):
    j = X[i]
    if j % 3 == 0:
        print(f"El número {j} es divisible por 3 y su resto es 0")
    elif j % 3 == 1:
        print(f"El número {j} no es divisible por 3 y su resto es 1") 
    else:
        print(f"El número {j} no es divisible por 3 y su resto es 2")       
    i +=1 # i = i+1    

El número 1 no es divisible por 3 y su resto es 1
El número 2 no es divisible por 3 y su resto es 2
El número 3 es divisible por 3 y su resto es 0
El número 4 no es divisible por 3 y su resto es 1
El número 5 no es divisible por 3 y su resto es 2
El número 6 es divisible por 3 y su resto es 0
El número 7 no es divisible por 3 y su resto es 1
El número 8 no es divisible por 3 y su resto es 2
El número 9 es divisible por 3 y su resto es 0
El número 10 no es divisible por 3 y su resto es 1


In [327]:
continuar = True
suma = 0
while continuar == True:
    suma = suma + 5
    print (suma)
    if suma == 45:
       continuar = False
      

5
10
15
20
25
30
35
40
45


In [328]:
X2[2]

TypeError: 'set' object is not subscriptable

Tarea: Inverstigar cómo llamar a un elemento de un conjunto en Python

Respuesta :

Cómo acceder a los elementos de un conjunto en Python
Dado que los conjuntos son colecciones desordenadas, en ellos no se guarda la posición en la que son insertados los elementos como ocurre en los tipos list o tuple. Es por ello que no se puede acceder a los elementos a través de un índice.

NumPy


NumPy es un juego de palabras que significa Python numérico (Numerical Python). Es una librería de código abierto que se utiliza para llevar a cabo tareas matemáticas con altísima eficiencia. Además, introduce estructuras de datos como los arrays multidimensionales, que se pueden operar entre ellos a alto nivel, sin meterse mucho en el detalle.


In [ ]:
import numpy as np


In [ ]:
# Generar un arreglo unidimensional

x1 = np.array([10,9,8,7,6,5,4,3,2,1])
x1


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
# Observar una posición en particular

x1[2]


np.int64(8)

In [ ]:
print(x1[2])

8


In [ ]:
print(f"El valor ubicado en la posición 2 es : {x1[2]}")

El valor ubicado en la posición 2 es : 8


In [ ]:
# Ajustar un valo r en particular
x1[0] = 0

print(x1)


[0 9 8 7 6 5 4 3 2 1]


In [ ]:
x1

array([0, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
# x1 + k; k= 10

x1 = x1 + 10
x1

array([10, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [ ]:
x1 += 10 # x1 = x1 + 10
x1

array([20, 29, 28, 27, 26, 25, 24, 23, 22, 21])

In [ ]:
# Consolidar los valores de x1 (np.sum())

suma_x1 = np.sum(x1)
print(f"La suma de todos los elementos de x1 es igual a : {suma_x1}")

La suma de todos los elementos de x1 es igual a : 245


In [ ]:
# Calculamos el promedio de los elementos de x1

n = len(x1)
promedio = suma_x1/n
promedio
print(f" El promedio de los elementos de x1 es: {promedio}")

 El promedio de los elementos de x1 es: 24.5


In [ ]:
# si usamos la definicon de NumPY (np.mean())

print(f"El promedio de los elementos de x1 es igual a: {np.mean(x1)}")


El promedio de los elementos de x1 es igual a: 24.5


In [332]:
# Desviación Estándar
np.std(x1)


np.float64(2.8722813232690143)

In [ ]:
# Operaciones Aritméticas ( (np.add(nomnre del arreglo, numero con el cual operaremos)))
# suma en numpy
x2 = np.add(x1,-10)
x2



array([10, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [ ]:
# Multiplicación

x1

array([20, 29, 28, 27, 26, 25, 24, 23, 22, 21])

In [329]:
x1*2

array([40, 58, 56, 54, 52, 50, 48, 46, 44, 42])

In [330]:
# np.multiply(nombre del arreglo con el cual operaremos)

np.multiply(x1,2)

array([40, 58, 56, 54, 52, 50, 48, 46, 44, 42])

In [ ]:
# Mediana
np.median(x1)



np.float64(24.5)

In [333]:
# Varianza np.var()

np.var(x1)

np.float64(8.25)

In [ ]:
# Mínimo y Máximo
# el comando np.argmin() permite conocer el índice donde se ubica el valor mínimo

minimo = np.argmin(x1)
print(f"El valor mínimo de x1 se ubica en la posición {minimo}")

# el valor mínimo del arreglo se busca con np.min()

min_x1 = np.min(x1)
print(f"El valor más pequeño de x1  es  {min_x1}")

# Máximo np.argmax()
# el comando np.argmax() permite conocer el índice donde se ubica el valor máximo

maximo = np.argmax(x1)
print(f"El valor máximo de x1 se ubica en la posición  {maximo}")

# el valor máximo del arreglo se busca con np.max()

max_x1 = np.max(x1)
print(f"El valor más grande de x1 es {max_x1}")

El valor mínimo de x1 se ubica en la posición 0
El valor más pequeño de x1  es  20
El valor máximo de x1 se ubica en la posición  1
El valor más grande de x1 es 29


TAREA 1 Numpy 10-07-25

Ejercicio 01: Crea un vector nulo (null vector) que tenga 10 elementos (★☆☆)

Un vector nulo es un array de una dimensión compuesto por ceros (0).
NOTA: Revisa la función np.zeros (https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)



In [ ]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Ejercicio 02: Crea un vector de unos que tenga 10 elementos (★☆☆)

NOTA: Revisa la función np.ones (https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Ejercicio 03: Investiga la función linspace de NumPy y crea un array que contenga 10 elementos (★☆☆)

NOTA: Revisa la función np.linspace (https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [ ]:
np.linspace(1.0,10.0, num=10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Ejercicio 04: Busca varias formas de generar un array con números aleatorios y crea un array 1D y dos arrays 2D
NOTA: Revisa las funciones np.random.rand (https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html),

 np.random.randint (https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html) y 
 
 np.random.randn (https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html)

In [ ]:
np.random.randint(5, size = 10)

array([0, 1, 4, 4, 1, 3, 1, 1, 0, 1])

In [ ]:
import numpy as np
np.random.rand(5,4)

array([[0.92949291, 0.2779126 , 0.41318885, 0.1736304 ],
       [0.57636269, 0.27079554, 0.65648995, 0.4525838 ],
       [0.86330106, 0.35032868, 0.04773532, 0.42959043],
       [0.43785098, 0.14529586, 0.84194626, 0.80184523],
       [0.34821374, 0.74472975, 0.67870665, 0.38825814]])

In [ ]:
3 + 2.5 * np.random.randn(2, 4)

array([[-1.36076651, -2.64190832,  2.30554631,  0.56879588],
       [ 3.85841262,  2.06883007,  1.2638943 ,  6.49314676]])

Ejercicio 05: Crea una matriz (array 2D) identidad de 5x5 (★☆☆)

NOTA: Revisa la función np.eye(https://numpy.org/devdocs/reference/generated/numpy.eye.html)

In [ ]:
np.eye(5,5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Ejercicio 06: Crea una matriz con números aleatorios de 3x2 y calcula el valor mínimo y máximo (★☆☆)

NOTA: Revisa la función np.min (https://numpy.org/devdocs/reference/generated/numpy.min.html) y np.max (https://numpy.org/devdocs/reference/generated/numpy.max.html)

In [ ]:
# Valor Mínimo
matriz_3x2 = np.random.rand(3,2)
print(matriz_3x2)
print(f"El valor Mínimo de la Matriz 3X2 es: {np.min(matriz_3x2)}")

# Valor Máximo
print(f"El valor Máximo de la Matriz 3x2 es: {np.max(matriz_3x2)}")

[[0.72528118 0.76599685]
 [0.55619088 0.54712809]
 [0.04480631 0.79070825]]
El valor Mínimo de la Matriz 3X2 es: 0.044806310518154646
El valor Máximo de la Matriz 3x2 es: 0.7907082453951735


Ejercicio 07: Crea un vector con números aleatorios de 30 elementos y calcula la media (★☆☆)

NOTA: Revisa la función np.mean (https://numpy.org/doc/stable/reference/generated/numpy.mean.html)

In [ ]:
a = np.random.rand(1, 30)
print("El Vector de números aleatorios es:")
print("")
print(a)
print("")
print(f"La Media del vector aletaorio es: {np.mean(a)} ")

El Vector de números aleatorios es:

[[0.0362266  0.08906204 0.83280689 0.31070193 0.99837397 0.26243558
  0.28079779 0.97617654 0.89628545 0.88653693 0.8507767  0.94218592
  0.54918403 0.92576928 0.69534309 0.41859245 0.18138735 0.51179257
  0.50925076 0.27069724 0.23189976 0.17688334 0.01499876 0.12835268
  0.36502465 0.90803983 0.77493814 0.24474177 0.63804147 0.69477321]]

La Media del vector aletaorio es: 0.5200692232389782 


Ejercicio 08: Convierte la lista [1, 2, 3] y la tupla (1, 2, 3) en arrays (★☆☆)

In [ ]:
l = [1, 2, 3]
t = (1, 2, 3)

al = np.array (l)
print(f"La lista convertida en arreglo es:{al}")
print("")
at = np.array(t)
print(f"La tupla convertida en arreglo es:{at}")
print("")

La lista convertida en arreglo es:[1 2 3]

La tupla convertida en arreglo es:[1 2 3]



Ejercicio 09: Invierte el vector del ejercicio anterior (★☆☆)

NOTA: Revisa la función np.flip (https://numpy.org/doc/stable/reference/generated/numpy.flip.html)

In [ ]:
import numpy as np
a = np.random.rand(1, 30)
b = np.flip(a,1)
print("El Vector de números aleatorios es:")
print("")
print(a)
print("")
print("El Vector invertido es:")
print("")
print(b)

El Vector de números aleatorios es:

[[0.18606418 0.85213443 0.33910497 0.21050538 0.66269891 0.19722531
  0.60833397 0.84892528 0.34497819 0.2373674  0.7981284  0.97221415
  0.31699323 0.22578647 0.07651076 0.82931059 0.68757484 0.09709464
  0.28701939 0.47001901 0.45187479 0.90462669 0.66130427 0.95755444
  0.11665584 0.00813911 0.34665897 0.80630385 0.53384078 0.99927775]]

El Vector invertido es:

[[0.99927775 0.53384078 0.80630385 0.34665897 0.00813911 0.11665584
  0.95755444 0.66130427 0.90462669 0.45187479 0.47001901 0.28701939
  0.09709464 0.68757484 0.82931059 0.07651076 0.22578647 0.31699323
  0.97221415 0.7981284  0.2373674  0.34497819 0.84892528 0.60833397
  0.19722531 0.66269891 0.21050538 0.33910497 0.85213443 0.18606418]]


Ejercicio 10: Cambia el tamaño de un array aleatorio de dimensiones 5x12 en 12x5 (★☆☆)

NOTA: Revisa la función np.reshape (https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [ ]:
a = np.random.rand(5,12)
b = np.reshape(a,(12,5))
print("El Arreglo aleatorio de dimensiones 5x12 es:")
print("")
print(a)
print("")
print("El Arreglo aleatorio cambiado a las dimensiones 12x5 es:")
print("")
print(b)

El Arreglo aleatorio de dimensiones 5x12 es:

[[8.51527234e-01 9.16874576e-01 6.93841219e-01 3.14789142e-01
  4.09140036e-01 6.15040171e-01 9.21970795e-01 9.82447379e-01
  8.42929306e-01 3.46158600e-01 2.12052436e-01 1.61201751e-01]
 [8.07825588e-01 5.64497924e-01 9.16478029e-01 9.62982716e-02
  5.95921705e-01 1.42676913e-01 4.21585831e-01 5.64032504e-01
  1.96427625e-01 4.20804913e-01 3.22941382e-01 5.05760591e-01]
 [2.87548911e-02 2.78495701e-01 2.11437336e-01 7.27616981e-01
  1.67116907e-01 8.95072471e-01 4.19178098e-01 5.54308822e-01
  4.29991652e-01 6.33112666e-01 9.91076884e-01 3.17708811e-01]
 [2.60123685e-01 1.38979920e-04 6.22769122e-01 6.40672569e-01
  9.85526235e-01 1.74543826e-01 8.12938765e-01 1.99556350e-01
  3.76831268e-01 4.60115455e-01 2.10688229e-01 1.91053880e-01]
 [4.28027434e-01 4.29552834e-01 4.87199941e-01 9.68762708e-02
  9.68439266e-01 5.97522952e-01 3.19543124e-01 1.67948144e-01
  8.48862029e-01 6.99920861e-01 6.62756181e-01 8.71256912e-01]]

El Arreglo aleato

Ejercicio 11: Convierte la lista [1, 2, 0, 0, 4, 0] en un array y obtén el índice de los elementos que no son cero (★★☆)

NOTA: Revisa la función np.where (https://numpy.org/devdocs/reference/generated/numpy.where.html)

In [ ]:
l = [1,2,0,0,4,0]
a = np.array(l)
print("El Arreglo obtenido de la lista [1,2,0,0,4,0] es:")
print("")
a
print(f"El índice de los elementos diferentes de cero son: {np.nonzero(a)}")

El Arreglo obtenido de la lista [1,2,0,0,4,0] es:

El índice de los elementos diferentes de cero son: (array([0, 1, 4]),)


Ejercicio 12: Convierte la lista [0, 5, -1, 3, 15] en un array, multiplica sus valores por -2 y obtén los elementos pares (★★☆)

In [ ]:
l = [0, 5, -1, 3, 15]
a = np.array(l)
a = a*(-2)
print("El Arreglo obtenido de la lista [0, 5, -1, 3, 15] es:")
print("")
a
print(f"Los elementos pares son: {a}")



El Arreglo obtenido de la lista [0, 5, -1, 3, 15] es:

Los elementos pares son: [  0 -10   2  -6 -30]


Ejercicio 13: Crea un vector aleatorio de 10 elementos y ordénalo de menor a mayor (★★☆)

NOTA: Revisa la función np.sort (https://numpy.org/doc/stable/reference/generated/numpy.sort.html)

In [ ]:
a = np.random.rand(1, 10)
print(f"El Vector aleatorio de 10 elementos es: {a}")
print("")
b = np.sort(a)
print(f"El Vector ordenado de menor a mayor es: {b}")
print("")


El Vector aleatorio de 10 elementos es: [[0.50275844 0.18573626 0.1610982  0.02232171 0.83909771 0.76687194
  0.79404319 0.43653355 0.67433899 0.1653327 ]]

El Vector ordenado de menor a mayor es: [[0.02232171 0.1610982  0.1653327  0.18573626 0.43653355 0.50275844
  0.67433899 0.76687194 0.79404319 0.83909771]]



Ejercicio 14: Genera dos vectores aleatorios de 8 elementos y aplica las operaciones de suma, resta y multiplicación entre ellos (★★☆)

NOTA: Revisa las funciones matemáticas: https://numpy.org/doc/stable/reference/routines.math.html

In [ ]:
a = np.random.rand(1, 8)
b = np.random.rand(1, 8)

s = np.sum(a)+np.sum(b)
print(f"El resultado de la suma de los vectores es: {s}")
print("")

d = np.diff(a)-np.diff(b)
print(f"El resultado de la resta de los vectores es: {d}")
print("")

p = np.prod(a)*np.prod(b)
print(f"El resultado de la multiplicación de los vectores es: {p}")


El resultado de la suma de los vectores es: 8.116760835217772

El resultado de la resta de los vectores es: [[-0.03006239 -0.0299153  -0.28328743 -0.12022258  0.22393549  0.65374343
  -0.26412558]]

El resultado de la multiplicación de los vectores es: 2.5883578524978877e-06


Ejercicio 15: Convierte la lista [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] en un array y transfórmalo en una matriz con filas de 3 columnas (★★★)

In [ ]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
a = np.array(l)
print("El Arreglo obtenido de la lista [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] es:")
print("")
print(a)
print("")
b = np.reshape(a, (4,3))
print("La matriz transformada en filas de 3 columnas es:")

b


El Arreglo obtenido de la lista [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] es:

[ 1  2  3  4  5  6  7  8  9 10 11 12]

La matriz transformada en filas de 3 columnas es:


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])