TAREA 1 Numpy 10-07-25

Ejercicio 01: Crea un vector nulo (null vector) que tenga 10 elementos (★☆☆)

Un vector nulo es un array de una dimensión compuesto por ceros (0).
NOTA: Revisa la función np.zeros (https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)



In [2]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Ejercicio 02: Crea un vector de unos que tenga 10 elementos (★☆☆)

NOTA: Revisa la función np.ones (https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Ejercicio 03: Investiga la función linspace de NumPy y crea un array que contenga 10 elementos (★☆☆)

NOTA: Revisa la función np.linspace (https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [4]:
np.linspace(1.0,10.0, num=10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Ejercicio 04: Busca varias formas de generar un array con números aleatorios y crea un array 1D y dos arrays 2D
NOTA: Revisa las funciones np.random.rand (https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html),

 np.random.randint (https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html) y 
 
 np.random.randn (https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html)

In [5]:
np.random.randint(5, size = 10)

array([2, 3, 4, 1, 1, 2, 4, 4, 2, 1])

In [6]:
import numpy as np
np.random.rand(5,4)

array([[0.16660168, 0.83634101, 0.73683715, 0.28216289],
       [0.87730543, 0.17417217, 0.30271535, 0.94698059],
       [0.19335935, 0.24300121, 0.31245606, 0.18166342],
       [0.39173398, 0.4541753 , 0.04256499, 0.63170955],
       [0.68217411, 0.21587686, 0.35341977, 0.13612586]])

In [7]:
3 + 2.5 * np.random.randn(2, 4)

array([[ 3.47832553,  1.3285611 , -0.42105679, -1.82983193],
       [-1.31838801,  4.05562284, -0.44879577,  1.56122044]])

Ejercicio 05: Crea una matriz (array 2D) identidad de 5x5 (★☆☆)

NOTA: Revisa la función np.eye(https://numpy.org/devdocs/reference/generated/numpy.eye.html)

In [8]:
np.eye(5,5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Ejercicio 06: Crea una matriz con números aleatorios de 3x2 y calcula el valor mínimo y máximo (★☆☆)

NOTA: Revisa la función np.min (https://numpy.org/devdocs/reference/generated/numpy.min.html) y np.max (https://numpy.org/devdocs/reference/generated/numpy.max.html)

In [9]:
# Valor Mínimo
matriz_3x2 = np.random.rand(3,2)
print(matriz_3x2)
print(f"El valor Mínimo de la Matriz 3X2 es: {np.min(matriz_3x2)}")

# Valor Máximo
print(f"El valor Máximo de la Matriz 3x2 es: {np.max(matriz_3x2)}")

[[0.09317122 0.62744147]
 [0.81166552 0.67206197]
 [0.29942258 0.88438946]]
El valor Mínimo de la Matriz 3X2 es: 0.09317122313568604
El valor Máximo de la Matriz 3x2 es: 0.8843894566855216


Ejercicio 07: Crea un vector con números aleatorios de 30 elementos y calcula la media (★☆☆)

NOTA: Revisa la función np.mean (https://numpy.org/doc/stable/reference/generated/numpy.mean.html)

In [10]:
a = np.random.rand(1, 30)
print("El Vector de números aleatorios es:")
print("")
print(a)
print("")
print(f"La Media del vector aletaorio es: {np.mean(a)} ")

El Vector de números aleatorios es:

[[0.24115345 0.44611636 0.23653195 0.89755885 0.07802776 0.92765355
  0.23866825 0.28144429 0.28824731 0.06650952 0.33630687 0.91083799
  0.24810039 0.63225547 0.01215513 0.88253125 0.40166875 0.9201406
  0.33113773 0.7978972  0.3488664  0.03877615 0.09464309 0.02228125
  0.36149403 0.05881891 0.75054229 0.38418473 0.25154381 0.57941908]]

La Media del vector aletaorio es: 0.4021837476977686 


Ejercicio 08: Convierte la lista [1, 2, 3] y la tupla (1, 2, 3) en arrays (★☆☆)

In [11]:
l = [1, 2, 3]
t = (1, 2, 3)

al = np.array (l)
print(f"La lista convertida en arreglo es:{al}")
print("")
at = np.array(t)
print(f"La tupla convertida en arreglo es:{at}")
print("")

La lista convertida en arreglo es:[1 2 3]

La tupla convertida en arreglo es:[1 2 3]



Ejercicio 09: Invierte el vector del ejercicio anterior (★☆☆)

NOTA: Revisa la función np.flip (https://numpy.org/doc/stable/reference/generated/numpy.flip.html)

In [12]:
import numpy as np
a = np.random.rand(1, 30)
b = np.flip(a,1)
print("El Vector de números aleatorios es:")
print("")
print(a)
print("")
print("El Vector invertido es:")
print("")
print(b)

El Vector de números aleatorios es:

[[0.06295618 0.81980724 0.32960457 0.48225658 0.84483017 0.61475331
  0.5285665  0.44343259 0.75853655 0.26652016 0.49491727 0.62868877
  0.53317357 0.65618612 0.84086356 0.20550718 0.00898892 0.99848151
  0.56992073 0.46202205 0.01615096 0.49520622 0.81723136 0.41669179
  0.28947584 0.44908516 0.61284008 0.75732489 0.86853136 0.63658754]]

El Vector invertido es:

[[0.63658754 0.86853136 0.75732489 0.61284008 0.44908516 0.28947584
  0.41669179 0.81723136 0.49520622 0.01615096 0.46202205 0.56992073
  0.99848151 0.00898892 0.20550718 0.84086356 0.65618612 0.53317357
  0.62868877 0.49491727 0.26652016 0.75853655 0.44343259 0.5285665
  0.61475331 0.84483017 0.48225658 0.32960457 0.81980724 0.06295618]]


Ejercicio 10: Cambia el tamaño de un array aleatorio de dimensiones 5x12 en 12x5 (★☆☆)

NOTA: Revisa la función np.reshape (https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [13]:
a = np.random.rand(5,12)
b = np.reshape(a,(12,5))
print("El Arreglo aleatorio de dimensiones 5x12 es:")
print("")
print(a)
print("")
print("El Arreglo aleatorio cambiado a las dimensiones 12x5 es:")
print("")
print(b)

El Arreglo aleatorio de dimensiones 5x12 es:

[[0.11554037 0.49640417 0.21601679 0.79183161 0.346195   0.02408526
  0.29529969 0.99669245 0.40740246 0.9336924  0.77305095 0.7107949 ]
 [0.66626638 0.1389828  0.92394817 0.32498733 0.31039938 0.34567007
  0.88256025 0.17777177 0.16649517 0.23466214 0.91287617 0.90650527]
 [0.79883389 0.79467183 0.50106049 0.76094798 0.93066016 0.44751567
  0.44677003 0.26784532 0.50314558 0.47146857 0.85626861 0.69893895]
 [0.14760923 0.31419196 0.32766614 0.11453634 0.24819086 0.46105339
  0.16995628 0.07251286 0.9176717  0.27534042 0.37308754 0.67048797]
 [0.60335849 0.39755575 0.26960243 0.87283045 0.11135969 0.88563724
  0.1799887  0.32203647 0.89086527 0.59482201 0.52236334 0.71936366]]

El Arreglo aleatorio cambiado a las dimensiones 12x5 es:

[[0.11554037 0.49640417 0.21601679 0.79183161 0.346195  ]
 [0.02408526 0.29529969 0.99669245 0.40740246 0.9336924 ]
 [0.77305095 0.7107949  0.66626638 0.1389828  0.92394817]
 [0.32498733 0.31039938 0.34567007 

Ejercicio 11: Convierte la lista [1, 2, 0, 0, 4, 0] en un array y obtén el índice de los elementos que no son cero (★★☆)

NOTA: Revisa la función np.where (https://numpy.org/devdocs/reference/generated/numpy.where.html)

In [14]:
l = [1,2,0,0,4,0]
a = np.array(l)
print("El Arreglo obtenido de la lista [1,2,0,0,4,0] es:")
print("")
a
print(f"El índice de los elementos diferentes de cero son: {np.nonzero(a)}")

El Arreglo obtenido de la lista [1,2,0,0,4,0] es:

El índice de los elementos diferentes de cero son: (array([0, 1, 4]),)


Ejercicio 12: Convierte la lista [0, 5, -1, 3, 15] en un array, multiplica sus valores por -2 y obtén los elementos pares (★★☆)

In [15]:
l = [0, 5, -1, 3, 15]
a = np.array(l)
a = a*(-2)
print("El Arreglo obtenido de la lista [0, 5, -1, 3, 15] es:")
print("")
a
print(f"Los elementos pares son: {a}")



El Arreglo obtenido de la lista [0, 5, -1, 3, 15] es:

Los elementos pares son: [  0 -10   2  -6 -30]


Ejercicio 13: Crea un vector aleatorio de 10 elementos y ordénalo de menor a mayor (★★☆)

NOTA: Revisa la función np.sort (https://numpy.org/doc/stable/reference/generated/numpy.sort.html)

In [16]:
a = np.random.rand(1, 10)
print(f"El Vector aleatorio de 10 elementos es: {a}")
print("")
b = np.sort(a)
print(f"El Vector ordenado de menor a mayor es: {b}")
print("")


El Vector aleatorio de 10 elementos es: [[0.37346489 0.03709916 0.54760046 0.47541867 0.82782702 0.88055151
  0.53316992 0.63209074 0.95544108 0.27691171]]

El Vector ordenado de menor a mayor es: [[0.03709916 0.27691171 0.37346489 0.47541867 0.53316992 0.54760046
  0.63209074 0.82782702 0.88055151 0.95544108]]



Ejercicio 14: Genera dos vectores aleatorios de 8 elementos y aplica las operaciones de suma, resta y multiplicación entre ellos (★★☆)

NOTA: Revisa las funciones matemáticas: https://numpy.org/doc/stable/reference/routines.math.html

In [24]:
a = np.random.rand(1, 8)
b = np.random.rand(1, 8)

s = np.sum(a)+np.sum(b)
print(f"El resultado de la suma de los vectores es: {s}")
print("")

d = np.diff(a)-np.diff(b)
print(f"El resultado de la resta de los vectores es: {d}")
print("")

p = np.prod(a)*np.prod(b)
print(f"El resultado de la multiplicación de los vectores es: {p}")


El resultado de la suma de los vectores es: 10.072884520406312

El resultado de la resta de los vectores es: [[-0.10813749  0.47278463 -0.16849286  0.11662507 -0.57832265  0.74696619
  -0.51529267]]

El resultado de la multiplicación de los vectores es: 5.325569129201237e-05


In [28]:
suma = a+b
print(suma)


[[1.46425075 1.06004225 0.93695047 0.40688272 1.72679148 1.2868306
  1.80962944 1.38150682]]


In [26]:
resta = a - b
print(resta)

[[-0.41196458 -0.52010207 -0.04731744 -0.2158103  -0.09918523 -0.67750788
   0.06945831 -0.44583436]]


In [27]:
prod = a*b
print(prod)

[[0.49357886 0.21329585 0.21890931 0.02974487 0.74299277 0.29922901
  0.81748356 0.4274482 ]]


Ejercicio 15: Convierte la lista [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] en un array y transfórmalo en una matriz con filas de 3 columnas (★★★)

In [19]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
a = np.array(l)
print("El Arreglo obtenido de la lista [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] es:")
print("")
print(a)
print("")
b = np.reshape(a, (4,3))
print("La matriz transformada en filas de 3 columnas es:")

b


El Arreglo obtenido de la lista [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] es:

[ 1  2  3  4  5  6  7  8  9 10 11 12]

La matriz transformada en filas de 3 columnas es:


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])